README.md, docs/submit_a_template.md
Added some clarification around the parts that I found most confusing and stumbled over trying to get going.
=> add details on where to find influx pkg

apache_postgresql/website_template.yml
Include new alerts and improved graphs
=> Update Apache+Postgresql template

docker/README.md, docker/docker.yml
docker/README -- Added alerts
docker/docker.yml:
1. Created alerts
2. Modified dashboard visually as well as changed queries to correct measurements for docker stats
=> Docker Alerts and Updated Docker Dashboard

aws_cloudwatch/README.md, aws_cloudwatch/aws_cloudwatch.yml, gcp_monitoring/README.md, gcp_monitoring/gcp_monitoring.yml, k8s/README.md, k8s/k8s.yml
Provide Telegraf configs for k8s, aws, gcp templates
Resolve compatibility of the name: properties ( _ to - conversion)
=> Telegraf configs for k8s, aws, gcp templates

Example_README.md, InfluxDBv2_Covid19_SouthAmerica/readme.md, apache_postgresql/README.md, aws_cloudwatch/README.md, currency_exchange_rates/README.md, docker/README.md, enviro_plus/README.md, gcp_monitoring/README.md, github/readme.md, influxdb2_oss_metrics/README.md, jenkins/README.md, k8s/README.md, linux_system/README.md, modbus/README.md, mongodb/readme.md, monitoring_influxdb_1.x/README.md, mysql_mariadb/readme.md, network_interface_performance/README.md, nginx_mysql/README.md, redis/README.md, sflow/README.md, telegraf/README.md, tomcat/readme.md, vsphere/readme.md, windows_system/README.md, x509/readme.md, zookeeper/readme.md
Add Quick Install instructions to all current Templates and the Example_README.md
=> Add Quick Install instructions

mssql/mssql.yml, mssql/readme.md
Add support for SQL Database in Azure (MSSQL powered)
Coordinated with xe-nvdk
=> feat (mssql): #126, reuse the existing template

network_interface_performance/network_interface_performance.yml
First attempt at providing network alert checking for network errors
=> Added alert for network errors

downsampling/README.md, downsampling/all_inputs/downsampling_tasks.yml, downsampling/all_inputs/telegraf.yml, downsampling/dashboard.yml, downsampling/monitoring_task.yml, downsampling/net_inputs/downsampling_tasks.yml, downsampling/net_inputs/telegraf.yml, downsampling/procstat_input/downsampling_tasks.yml, downsampling/procstat_input/telegraf.yml
added a set of tasks to download all plugin data
added net, netstat, and procstat configurations
updated readme
=> feat(downsampling): adding all, net, procstat configs

downsampling/README.md, downsampling/dashboard.yml, downsampling/smart_input/downsampling_tasks.yml, downsampling/smart_input/telegraf.yml
- adds support for S.M.A.R.T. input
- adds support for downsampling bool values
- updates dashboard queries to be more performant
=> feat(downsampling): added smart input, handle bool values

.github/workflows/main.yml
Adds a workflow which will load all `yml` files into an oss influx instance to ensure they work on every PR and merge to master.
An example of what this looks like can be found here: https://github.com/russorat/community-templates/actions
=> feat(workflow): add CI

postgresql/postgres.yml
just removing newlines, but really testing github actions.
=> chore(postgres): removing newlines

downsampling/dashboard.yml, downsampling/monitoring_task.yml
updates the monitoring task to work for all tasks, not just downsampling
=> feat(downsampling): updating monitoring task

fortnite/README.md, fortnite/get_fn_stats.py
python 2 or python 3 can be used to run script.
=> Remove python 3 requirement and update season

Example_readme.md, InfluxDBv2_Covid19_SouthAmerica/readme.md, apache_jmeter/readme.md, apex_legends/readme.md, csgo/readme.md, docs/best_practices.md, endpoint-security-state/readme.md, fortnite/readme.md, github/readme.md, haproxy/readme.md, jboss_wildfly/readme.md, minio/readme.md, mongodb/readme.md, mssql/readme.md, mysql_mariadb/readme.md, postgresql/readme.md, snmp/readme.md, speedtest/readme.md, telegraf/readme.md, tomcat/readme.md, vsphere/readme.md, x509/readme.md, zookeeper/readme.md
this fixes rendering issues in the UI
=> fix(readmes): fixes spacing in the readmes for rendering

kafka/readme.md
references idpe #8810 (community templates readmes not showing up correctly)
=> Fix the spacing on kafka readme for measurement dropdowns

algorithmia/algorithmia.yml, algorithmia/readme.md
Fix description of the `INFLUX_HOST` environment variable and some of the formatting in the README.
=> Update Algorithmia README

influxdb2_operational_monitoring/influxdb2_operational_monitoring.yml
=> fix: labels

covid19-southamerica/readme.md
update the url to the covid.url file
=> update the url to the covid.url file

raspberry-pi/raspberry-pi-system.yml, raspberry-pi/readme.md
modify the bucket in the telegraf config
update dashboard to use the bucket
add vcgencmd location for Ubuntu 64
update readme
=> Rasp PI Template updates

node_js/readme.md
=> fix: update readme.md

usage_dashboard/usage_dashboard.yml
- Task for slack notification no longer triggers an error 
- Dashboard usage data section titles use Notes instead of the 'array' text cells
=> Updated Task for slack notification

.github/workflows/main.yml
This updates the CI process to use a new github action i set up for influxdb.
=> feat: use new influxdb github action

mysql_mariadb/mysql_mariadb.yml
None
I just added the variables (bucket and mysql_host), which allow to be more flexibile and permit a user to monitor more than one mysql/mariadb server.
I also created the dashboard for glusterfs storage. I want to know how i can add the dashboard under influxdata/community-templates repository. Can you please help me and tell me the procedure to follow?
Thanks.
=> Add variables bucket and mysql_host

README.md, sample-data/bitcoin.task.yml, sample-data/earthquake.task.yml, sample-data/ndbc.task.yml, sample-data/readme.md, sample-data/sample-data.yml, sample-data/sample_data.bucket.yml, sample-data/sensor.task.yml
=> Add sample data template

influxdb-enterprise-1x/enterprise.yml
OK, I changed the query to pull the number of data nodes to a unique count of hosts that match a regex of the 'data' host name. Seems to work ok
=> changed data node count cell

sample-data/bitcoin.task.yml, sample-data/earthquake.task.yml, sample-data/ndbc.task.yml, sample-data/sample-data.yml, sample-data/sensor.task.yml
updates the sample data template to use the s3 urls instead of github.
=> fix: updating sample data urls
